Modules/Tramites/Routes/web.php
	Route::get('tramitesenrevision', 'TramAlcaldiaCabController@revisionAnalista');
	Route::get('tramitesrevisar', 'TramAlcaldiaCabController@tramitesRevisar')->name('tramites.revisar');
	Route::get('tramitesrevisarajax', 'TramAlcaldiaCabController@tramitesRevisarAjax')->name('tramites.revisar.ajax');
	Route::get('tramitesdevueltos', 'TramAlcaldiaCabController@indexDevueltos');
    Route::get('calcular_fecha_despachar/{tramite}/{fecha_inicial}', 'TramAlcaldiaCabController@calcular_fecha_despachar');
    Route::get('despachartramite', 'TramAlcaldiaCabController@editdespacho');
	Route::get('finalizartramite', 'TramAlcaldiaCabController@editFinalizar')->name('tramite.editfinalizar');
    Route::post('devolver/{id}/{timeline}', 'TramAlcaldiaCabController@devolver');
    Route::get('asignados', 'AsignarAnalistasController@asignados');
	Route::get('asignadoscontestados', 'AsignarAnalistasController@asignadosContestados');
	Route::get('asignadosajax', 'AsignarAnalistasController@asignadosAjax')->name('asignados.ajax');
	Route::post('asignaranalista/{id}', 'AsignarAnalistasController@asignarAnalista');
	Route::post('guardarinformeanalista/{id}', 'AsignarAnalistasController@guardarInformeAnalista');
	Route::post('enviarsecretaria/{id}', 'AsignarAnalistasController@enviarSecretaria');
    Route::post('archivartramiteanalista/{id}', 'AsignarAnalistasController@archivarTramiteAnalista');
    Route::get('obtenerusuario/{id}', 'TramAlcaldiaCabController@obtenerUsuario');

    Route::get('tramitesexternos', 'TramAlcaldiaCabController@tramites');
	Route::get('tramitesexternosajax', 'TramAlcaldiaCabController@tramitesAjax')->name('tramites.externos.ajax');
	Route::get('tramitesexternosportal', 'TramAlcaldiaCabController@tramitesPortal');
	Route::get('tramitesbusqueda', 'TramAlcaldiaCabController@tramitesBusqueda');
    Route::get('tramitesingresadosajax', 'TramAlcaldiaCabController@tramitesBusquedaAjax')->name('tramites.busqueda.ajax');

    Route::get('reservados', 'TramAlcaldiaProcesosController@tramitesReservados');
	Route::get('tramitesreservadosajax', 'TramAlcaldiaProcesosController@tramitesReservadosAjax');
	Route::get('concopia', 'TramAlcaldiaProcesosController@conCopia');
	Route::get('tramitesconcopiasajax', 'TramAlcaldiaProcesosController@tramitesConCopiasAjax');
	Route::post('desvinculartramite/{id}', 'TramAlcaldiaProcesosController@desvincularTramite');
	Route::post('solicitarinforme/{id}', 'TramAlcaldiaProcesosController@solicitarInforme')->name('solicitarinforme');
	Route::post('notificarcoordinador/{id}/{direccion}', 'TramAlcaldiaProcesosController@notificarCoordinador');
	Route::post('enviaraprobacion/{id}', 'TramAlcaldiaProcesosController@enviarAprobacion');
	Route::get('solicitudesinforme', 'TramAlcaldiaProcesosController@solicitudesInforme');
	Route::post('guardarinforme/{id}', 'TramAlcaldiaProcesosController@guardarInforme');
	Route::post('devolverdirector/{id}/{id_direccion}', 'TramAlcaldiaProcesosController@devolverDirector');
	Route::post('reservartramite', 'TramAlcaldiaProcesosController@reservarTramite');
	Route::post('finalizartramitedirector/{id}', 'TramAlcaldiaProcesosController@finalizarTramiteDirector');
	Route::post('finalizarsubdirector/{id}', 'TramAlcaldiaProcesosController@finalizarTramiteSubdirector');
	Route::post('finalizarimcompleto/{id}', 'TramAlcaldiaProcesosController@finalizarImcompleto');
	Route::get('obtenertipostramite/{area}', 'TramAlcaldiaProcesosController@obtenerTiposTramite');
	Route::post('eliminararchivotramite', 'TramAlcaldiaProcesosController@eliminarArchivo');
	Route::post('subirarchivotramite', 'TramAlcaldiaProcesosController@subirArchivo')->name('subirarchivo.tramite');
	Route::post('subiralcancetramite', 'TramAlcaldiaProcesosController@subirArchivoAlcance')->name('subiralcance.tramite');
	Route::post('subiracuerdo', 'TramAlcaldiaProcesosController@subirArchivoAcuerdo')->name('subiracuerdo.tramite');
	Route::post('eliminaracuerdo', 'TramAlcaldiaProcesosController@eliminarArchivoAcuerdo');
	Route::get('cargaracuerdo/{cedula}', 'TramAlcaldiaProcesosController@cargarArchivoAcuerdo');
	Route::post('eliminararchivoalcance', 'TramAlcaldiaProcesosController@eliminarArchivoAlcance');
	Route::post('enviarrespuestaciudadano/{id}', 'TramAlcaldiaProcesosController@enviarRespuestaCiudadano');
	Route::post('finalizarconpago/{id}', 'TramAlcaldiaProcesosController@finalizarConPago');
	Route::post('enviardonacion/{id}', 'TramAlcaldiaProcesosController@enviarDonacion');
    Route::post('devolverventanilla/{id}', 'TramAlcaldiaProcesosController@devolverVentanilla');

    Route::get('tramitesingresados', 'TramAlcaldiaProcesosController@tramitesIngresadoPortal');
	Route::get('tramitesingresadoajax', 'TramAlcaldiaProcesosController@tramitesIngresadoPortalAjax')->name('ingresados.portal.ajax');
	Route::get('tramitesingresadosfinalizados', 'TramAlcaldiaProcesosController@tramitesFinalizadosPortal');
	Route::get('tramitesingresadosfinalizadosajax', 'TramAlcaldiaProcesosController@tramitesFinalizadosPortalAjax')->name('finalizados.portal.ajax');
	Route::post('archivartramite/{id}', 'TramAlcaldiaProcesosController@archivarTramite');
	Route::post('archivartramiteinforme/{id}', 'TramAlcaldiaProcesosController@archivarTramiteInforme');
	Route::get('tramitesarchivados', 'TramAlcaldiaProcesosController@tramitesArchivados');
	Route::get('tramitesarchivadosajax', 'TramAlcaldiaProcesosController@tramitesArchivadosAjax')->name('tramites.archivados.ajax');
	Route::get('tramitesnotificar', 'TramAlcaldiaProcesosController@tramitesNotificar');
	Route::get('tramitesnotificarajax', 'TramAlcaldiaProcesosController@tramitesNotificarAjax');
	Route::get('obteneranalistaspordireccion/{id}', 'TramAlcaldiaCabController@obtenerAnalistasPorDireccion');
    Route::post('devolvertramiteinforme/{id}', 'TramAlcaldiaProcesosController@devolverTramiteInforme');

    Route::get('rechazadostramitesAlcaldiajax', 'TramAlcaldiaCabController@rechazadostramitesAlcaldiajax');
	Route::get('tramitesAlcaldiaDevueltosajax', 'TramAlcaldiaCabController@tramitesAlcaldiaDevueltosajax');
	Route::get('tramitesAlcaldiajax', 'TramAlcaldiaCabController@tramitesAlcaldiajax');
	Route::get('tramitesAlcaldiaPenidentesajax', 'TramAlcaldiaCabController@tramitesAlcaldiaPenidentesajax');
	Route::get('tramitesAlcaldiaDespachadosajax', 'TramAlcaldiaCabController@tramitesAlcaldiaDespachadosajax');
	Route::get('tramitesAlcaldiaEjecutadosajax', 'TramAlcaldiaCabController@tramitesAlcaldiaEjecutadosajax');
	Route::get('tramitesAlcaldiaFinalizadosajax', 'TramAlcaldiaCabController@tramitesAlcaldiaFinalizadosajax');
	Route::get('recibo/{id}', 'TramAlcaldiaCabController@recibo');

    /**AUTORIZACIONES PARA FIRMA QR (TRÁMITES INTERNOS)*/
    Route::resource('autorizaciones', 'TramInternoAutorizacionController');
	Route::get('tramitesAutorizacionesjax', 'TramInternoAutorizacionController@tramitesAutorizacionesjax');
	Route::get('descargarFormatoAutorizacion/{cedula}', 'TramInternoAutorizacionController@descargarFormatoAutorizacion');

    /**TRÁMITES INTERNOS */
    Route::get('tramitesinternos/recibidos', 'TramitesInternosController@recibidos')->name('tramites.recibidos');
	Route::get('tramitesinternos/copia', 'TramitesInternosController@conCopia')->name('tramites.copia');
	Route::get('tramitesinternos/contestados', 'TramitesInternosController@contestados')->name('tramites.contestados');
	Route::get('tramitesinternos/archivados', 'TramitesInternosController@archivados')->name('tramites.archivados');
	Route::get('tramitesinternos/borradores', 'TramitesInternosController@borradores')->name('tramites.borradores');
	Route::get('tramitesinternos/oficios', 'TramitesInternosController@oficios')->name('oficios.index');
	Route::get('tramitesinternos/oficiosajax', 'TramitesInternosController@oficiosAjax')->name('oficios.ajax');
	Route::get('tramitesinternoshistorial/{id}', 'TramitesInternosController@show')->name('internos.show');
	Route::get('agregarhistorial', 'TramitesInternosController@agregarHistorial');
	Route::post('asignaranalistainternos/{id}', 'TramitesInternosController@asignarAnalistaInternos');
	Route::get('tramitesinternos/asignados', 'TramitesInternosController@asignados');
	Route::get('cambiarremitente', 'TramitesInternosController@cambiarRemitente');
	Route::post('eliminarBorrador', 'TramitesInternosController@eliminarBorrador');

	Route::resource('tramitesinternos', 'TramitesInternosController');
	Route::get('indexajax', 'TramitesInternosController@indexajax')->name('tramites.ajax');
	Route::get('copiaedit/{id}', 'TramitesInternosController@copiaEdit')->name('copia.edit');
	Route::get('revisionedit/{id}', 'TramitesInternosController@revisionEdit')->name('revision.edit');
	Route::get('asignaranalistas/{id}', 'TramitesInternosController@asignarAnalistas')->name('asignar.analista');
	Route::put('guardarrevision/{id}', 'TramitesInternosController@guardarRevision')->name('revision.store');
	Route::post('desvinculartramiteinterno/{id}', 'TramitesInternosController@desvincularTramiteInterno');
	Route::post('archivartramiteinterno/{id}', 'TramitesInternosController@archivarTramite');
    Route::get('consultardireccion', 'TramitesInternosController@consultardireccion');
    Route::get("getDate", "TramitesInternosController@getDate");

    Route::resource('direcciones', 'DireccionesController');
	Route::get("getusuariosdireccion","DireccionesController@getusuariosdireccion");
	Route::get("getcordinaciondireccion","DireccionesController@getcordinaciondireccion");
	Route::get("direccionesajax", "DireccionesController@direccionesajax");

	////firma electronica
	Route::post('generarDocumento', 'TramitesInternosController@generarDocumento')->name('generarDocumento');
	Route::get('generarDocumento', 'TramitesInternosController@generarDocumento')->name('generarDocumento');
	Route::get('validarDocumento', 'TramitesInternosController@validarDocumento')->name('validarDocumento');
	Route::post('generarCodigo', 'TramitesInternosController@generarCodigo')->name('generarCodigo');
});

Modules/Tramites/Resources/views/tramitesinternos/create.blade.php
@extends('layouts.layout')

@section ('titulo') {{ $configuraciongeneral[0] }} @stop

<style>
    #swal2-content {
        font-size: 1.5em;
    }
</style>

@section('contenido')
<div class="row animated fadeInRight">
    <div class="col-lg-12">
        <div class="imgback">
            <h1>{{ $configuraciongeneral[4] }}</h1>

            <div class="ibox float-e-margins">
                {{-- <div class="ibox-title">
                    <div>
                        <a href="{{ route('tramitesinternos.index') }}" class="btn btn-primary ">Todos</a>
                        <a href="{{ route('tramitesinternos.create') }}" class="btn btn-default ">Nuevo</a>
                    </div>
                </div> --}}

                <div class="ibox-content">
                    @include('tramites::tramitesinternos.errors')
                    @if ($configuraciongeneral[3] == 'crear')
                        {!! Form::open(['route' => $configuraciongeneral[1], 'method' => 'POST', 'id' => "form", 'class' => 'form-horizontal','files' => true]) !!}
                            @include('tramites::'.$configuraciongeneral[2], ['edicion' => false])
                    @elseif($configuraciongeneral[3] == 'editar')
                        {!! Form::model($tabla, ['route' => [$configuraciongeneral[1], Crypt::encrypt($tabla->id)], 'method' => 'PUT', 'id' => "form", 'class' => 'form-horizontal','files' => true]) !!}
                            @include('tramites::'.$configuraciongeneral[2], ['edicion' => true])
                    @endif
                        {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
</div>

@include("vistas.includes.mainjs")

@if(isset($timelineTramiteInternos))
    <div class="ibox float-e-margins">
        <div class="ibox-title">
            <h1>Historial</h1>
            <div hidden>{{ $contador=0 }}</div>
            <div id="vertical-timeline" class="vertical-container dark-timeline center-orientation">
                <div class="vertical-timeline-block">
                    @foreach ($timelineTramiteInternos as $item)
                        @php
                            $arraycolores = ["#00CED1","#5F9EA0","#4682B4","#87CEFA","#00BFFF","#7B68EE","#E0FFFF","#AFEEEE","#7FFFD4","#40E0D0","#191970","#000080"];
                            $color_aleatoreo = $arraycolores[array_rand($arraycolores)];
                        @endphp
                        <div class="vertical-timeline-block">
                            <div class="vertical-timeline-icon" style='background-color:{{$color_aleatoreo}}'>
                            </div>
                            <div class="vertical-timeline-content">
                                @if ($contador==0)
                                    <h2><i class="fa fa-save"></i>  Inicial</h2>
                                @elseif($contador>=1)
                                    <h2><i class="fa fa-pencil"></i> Actualización</h2>
                                @endif
                                <div hidden> {{$contador+=1}} </div>
                                <p>
                                    <pre style="text-align: left; white-space: pre-line;">
                                        <strong>Fecha de registro: </strong>{{ $item->created_at }}
                                        <strong>Numero de trámite: </strong>{{ $item->numtramite }}
                                        <strong>Remitente: </strong>  {{ $item->remitente }}
                                        <strong>Asunto: </strong>  {{ $item->asunto }}
                                        <strong>Tipo de trámite: </strong>  {{ $item->tipo_tramite }}
                                        <strong>Estado: </strong>  {{ mb_strtoupper($item->estado) }}
                                        <br>
                                        <strong>Modificado Por: </strong>{{ $item->usuario }}
                                    </pre>
                                    @if (isset($timelineTramiteResp))
                                        <strong><i class="fa fa-users"></i> Delegados</strong>
                                        <pre style="text-align: left; white-space: pre-line;">
                                            @foreach ($timelineTramiteResp as  $i)
                                                <strong>Nombre: </strong>{{$i->name}}
                                            @endforeach
                                        </pre>
                                    @endif
                                </p>
                                <span class="vertical-date">
                                    {{fechas(2,$item->updated_at)}} <br/>
                                    <small>{{fechas(1000,$item->updated_at)}} </small>
                                </span>
                            </div>
                        </div>
                    @endforeach
                </div>
            </div>
        </div>

    </div>
@endif
@stop

@section('scripts')
    <script src="{{ asset('js/tramitesinternos.js').'?v='.rand(1,1000) }}"></script>
@endsection

Modules/Tramites/Resources/views/tramitesinternos/errors.blade.php
@if ($errors->any())
    <div class="row">
        <div class="col-12 col-md-6 col-md-offset-3">
            <div class="alert alert-danger alert-dismissible">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                <ul>
                    @foreach ($errors->all() as $error)
                        <li class="text-center">{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
        </div>
    </div>
@endif

@if(session('warning'))
    <div class="row ">
        <div class="col-12 col-md-6 col-md-offset-3">
            <div class="alert alert-warning alert-dismissible text-center">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                {{ session('warning') }}
            </div>
        </div>
    </div>
@endif

@if (Session::has('message'))
<script>
    $(document).ready(function() {
        toastr["success"]("{{ Session::get('message') }}");
    });
</script>
@endif

Modules/Tramites/Resources/views/tramitesinternos/index.blade.php
@extends(request()->has("menu") ? 'layouts.layout_basic_no_head': 'layouts.layout')

@section ('titulo') {{ $configuraciongeneral[0] }} @stop

@section('contenido')

<style>
    .swal2-textarea {
        font-size: 2em;
    }
    #swal2-content {
        font-size: 1.5em;
    }
</style>

<div class="row wrapper border-bottom">
    <div class="col-lg-10">
        <h1 class="font-bold text-primary">{{ $configuraciongeneral[4] }}</h1>
    </div>
</div>
<div class="animated fadeInRight">
    <div class="row">
        <div class="col-lg-12">
            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <div class="ibox-tools">
                    </div>
                </div>
                <div class="ibox-content">
                    @include('tramites::tramitesinternos.errors')
                    @if(isset($crear_editar)  && $crear_editar == 'SI')
                        <div>
                            <a href="{{ route('tramitesinternos.index') }}" class="btn btn-primary ">Todos</a>
                            <a href="{{ route('tramitesinternos.create') }}" class="btn btn-default ">Nuevo</a>
                        </div>
                    @endif
                    {{-- {{dd($estado)}} --}}
                    <div class="row">
                        <table class="table table-striped table-bordered table-hover display" id="tabla-tramites" cellspacing="0" width="100%">
                            <thead>
                                <tr>
                                    <th>ID</th>
                                    <th>N° de trámite</th>
                                    <th>Adjunto</th>
                                    <th>Anexos</th>
                                    <th>Remitente</th>
                                    <th>Asunto</th>
                                    <th>Tipo</th>
                                    <th>Fecha de registro</th>
                                    <th>Para</th>
                                    <th>Con copia</th>
                                    @if($estado == 'ANALISTA' || $estado == 'ASIGNADO')
                                        <th>Asignado a</th>
                                    @endif
                                    @if($tipo_envio == 'BORRADOR')
                                        <th>elaborado por</th>
                                    @endif
                                    @if ($estado == 'ASIGNADO' || $estado == 'INICIAL' || $estado == 'ARCHIVADO' || $estado == 'ANALISTA')
                                        <th>Acciones</th>
                                    @endif
                                </tr>
                            </thead>
                        </table>
                        @if(isset($analistas) && count($analistas) > 0)
                            @include('vistas.modal_analistas', ['analistas' => $analistas])
                        @endif
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

@section('scripts')
    <script src="{{ asset('js/tramitesinternos.js').'?v='.rand(1,1000) }}"></script>
    <script>
        var tablaTramitesIntenos;

        $(function() {
            $('.selective-tags').selectize({
                plugins: ['remove_button'],
                persist: false,
                create: true,
                render: {
                    item: function(data, escape) {
                        return '<div>"' + escape(data.text) + '"</div>';
                    }
                },
                onDelete: function(values) {
                    return confirm('Esta seguro de borrar la selección?');
                }
            });

            tablaTramitesIntenos = $('#tabla-tramites').DataTable({
                processing: true,
                serverSide: true,
                responsive: true,
                order: [[ 0, 'DESC' ]],
                ajax: '{!! route('tramites.ajax') !!}?estado={{$estado}}&tipo_envio={{$tipo_envio}}',
                language: { url: '../../language/es.json' },
                lengthMenu: [[10, 25, 50, 100, -1], [10, 25, 50, 100, 'TODOS']],
                // dom: 'Blfrtip',
                // buttons: [
                //     {
                //         extend: 'pdfHtml5',
                //         title: 'Trámites internos',
                //         text: '<i class="fa fa-file-pdf"></i> PDF'
                //     },
                //     {
                //         extend: 'excelHtml5',
                //         title: 'Trámites internos',
                //         footer: true
                //     },
                // ],
                columns: [
                    { data: 'id', name: 'id' },
                    { data: 'numtramite', name: 'numtramite' },
                    { data: 'memo', name: 'memo' },
                    { data: 'anexos', name: 'anexos' },
                    { data: 'remitente.name', name: 'remitente.name' },
                    { data: 'asunto', name: 'asunto' },
                    { data: 'tipo_tramite', name: 'tipo_tramite' },
                    { data: 'created_at', name: 'created_at' },
                    { data: 'asignados', name: 'asignados' },
                    { data: 'copias', name: 'copias' },
                    @if($estado == 'ANALISTA' || $estado == 'ASIGNADO')
                        { data: 'analistas', name: 'analistas' },
                    @endif
                    @if($tipo_envio == 'BORRADOR')
                        { data: 'elaborado_por', name: 'elaborado_por' },
                    @endif
                    @if ($estado == 'ASIGNADO' || $estado == 'INICIAL' || $estado == 'ARCHIVADO' || $estado == 'ANALISTA')
                        { data: 'action', name: 'action', orderable: false, searchable: false }
                    @endif
                ]
            });
        });
    </script>



    <script>
        $(document).ready(function() {
            let queryParam = getParameterByName('ti')
            if(queryParam != '')
            {
                console.log(queryParam)
                $('#tabla-tramites').on('draw.dt', function () {
                    console.log('draw')
                    $(`#${queryParam}`).trigger('click')
                });
            }
        })
        function getParameterByName(name) {
            name = name.replace(/[\[]/, "\\[").replace(/[\]]/, "\\]");
            var regex = new RegExp("[\\?&]" + name + "=([^&#]*)"),
            results = regex.exec(location.search);
            return results === null ? "" : decodeURIComponent(results[1].replace(/\+/g, " "));
        }
    </script>

@endsection

Modules/Tramites/Resources/views/tramitesinternos/oficios.blade.php
@extends(Input::has("menu") ? 'layout_basic_no_head':'layout' )

@section ('titulo') {{ $configuraciongeneral[0] }} @stop

@section('contenido')
<div class="row wrapper border-bottom">
    <div class="col-lg-10">
        <h1 class="font-bold text-primary">{{ $configuraciongeneral[4] }}</h1>
    </div>
</div>
<div class="animated fadeInRight">
    <div class="row">
        <div class="col-lg-12">
            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <div class="ibox-tools">
                        {{-- <a class="collapse-link">
                            <i class="fa fa-chevron-up"></i>
                        </a> --}}
                        {{-- <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                            <i class="fa fa-wrench"></i>
                        </a> --}}
                        {{-- <ul class="dropdown-menu dropdown-user">
                            <li><a href="#">Listar todos</a>
                            </li>
                            <li><a href="#">Nuevo</a>
                            </li>
                        </ul> --}}
                        {{-- <a class="close-link">
                            <i class="fa fa-times"></i>
                        </a> --}}
                    </div>
                </div>

                <div class="ibox-content">
                    @include('tramites::tramitesinternos.errors')
                    @if(isset($crear_editar)  && $crear_editar == 'SI')
                        <div>
                            <a href="{{ route('tramitesinternos.index') }}" class="btn btn-primary ">Todos</a>
                            <a href="{{ route('tramitesinternos.create') }}" class="btn btn-default ">Nuevo</a>
                        </div>
                    @endif
                    <div class="row">
                        <table class="table table-striped table-bordered table-hover display" id="tabla-tramites" cellspacing="0" width="100%">
                            <thead>
                                <tr>
                                    <th>ID</th>
                                    <th>N° de trámite</th>
                                    <th>Memo</th>
                                    <th>Anexos</th>
                                    <th>Remitente</th>
                                    <th>Asunto</th>
                                    <th>Fecha de registro</th>
                                    <th>Para</th>
                                    <th>Con copia</th>
                                </tr>
                            </thead>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

@section('scripts')
    <script src="{{ asset('js/tramitesinternos.js').'?v='.rand(1,1000) }}"></script>

    <script>
        $(function() {
            $('#tabla-tramites').DataTable({
                processing: true,
                serverSide: true,
                responsive: true,
                order: [[ 0, 'DESC' ]],
                ajax: '{!! route('oficios.ajax') !!}',
                language: { url: '../../language/es.json' },
                lengthMenu: [[10, 25, 50, 100, -1], [10, 25, 50, 100, 'TODOS']],
                // dom: 'Blfrtip',
                // buttons: [
                //     {
                //         extend: 'pdfHtml5',
                //         title: 'Trámites internos',
                //         text: '<i class="fa fa-file-pdf"></i> PDF'
                //     },
                //     {
                //         extend: 'excelHtml5',
                //         title: 'Trámites internos',
                //         footer: true
                //     },
                // ],
                columns: [
                    { data: 'id', name: 'id' },
                    { data: 'numtramite', name: 'numtramite' },
                    { data: 'oficio', name: 'oficio' },
                    { data: 'anexos', name: 'anexos' },
                    { data: 'remitente.name', name: 'remitente.name' },
                    { data: 'asunto', name: 'asunto' },
                    { data: 'created_at', name: 'created_at' },
                    { data: 'asignados', name: 'asignados' },
                    { data: 'copias', name: 'copias' },
                ]
            });
        });
    </script>
@endsection